regex:
  banks:
      - name: 'TTB'
        test_str: 'มีเงินเข้า1,000.00บ.จาก KTB x7336 MR. CHAIYASART 01/01/20@01:00'
        regex: 'มีเงินเข้า([\d,]+\.\d+บ).+จาก\s([A-Z]+)\s(\w+)\s(MR\.\s[A-Z]+)\s.+(\d{2}/\d{2}/\d{2}@\d{2}:\d{2})'
      - name: 'SCB'
        test_str: 'มีเงินเข้า1,000.00บ.จาก SCB MR. JOHN DOE 01/01/20@01:00'
        regex: 'มีเงินเข้า([\d,]+\.\d+บ).+จาก\s([A-Z]+)\s(\w+)\s(MR\.\s[A-Z]+)\s.+(\d{2}/\d{2}/\d{2}@\d{2}:\d{2})'
      - name: 'KBANK'
        test_str: 'มีเงินเข้า1,000.00บ.จาก KBANK MR. JOHN DOE 01/01/20@01:00'
        regex: 'มีเงินเข้า([\d,]+\.\d+บ).+จาก\s([A-Z]+)\s(MR\.\s[A-Z]+)\s.+(\d{2}/\d{2}/\d{2}@\d{2}:\d{2})'
      - name: 'KTB'
        test_str: 'มีเงินเข้า1,000.00บ.จาก KTB MR. JOHN DOE 01/01/20@01:00'
        regex: 'มีเงินเข้า([\d,]+\.\d+บ).+จาก\s([A-Z]+)\s(MR\.\s[A-Z]+)\s.+(\d{2}/\d{2}/\d{2}@\d{2}:\d{2})'
      - name: 'BBL'
        test_str: 'มีเงินเข้า1,000.00บ.จาก BBL MR. JOHN DOE 01/01/20@01:00'
        regex: 'มีเงินเข้า([\d,]+\.\d+บ).+จาก\s([A-Z]+)\s(MR\.\s[A-Z]+)\s.+(\d{2}/\d{2}/\d{2}@\d{2}:\d{2})'
      - name: 'BAY'
        test_str: 'มีเงินเข้า1,000.00บ.จาก TMB MR. JOHN DOE 01/01/20@01:00'
        regex: 'มีเงินเข้า([\d,]+\.\d+บ).+จาก\s([A-Z]+)\s(MR\.\s[A-Z]+)\s.+(\d{2}/\d{2}/\d{2}@\d{2}:\d{2})'
    